# Generated by Django 2.2.6 on 2019-10-15 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('E_mail', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('saudi arabia +966', 'SAUDI ARABIA +966'), ('oman +968', 'OMAN +968'), ('kuwait +965', 'KWUAIT +965'), ('Qatar +948', 'QATAR +948')], max_length=250, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('phone_code', models.IntegerField(null=True)),
                ('nationality', models.CharField(choices=[('1', 'خليجي'), ('2', 'ليس خليجي')], max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(null=True, upload_to='images/')),
                ('published_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
