# Generated by Django 2.2.4 on 2019-10-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('E_mail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
