# Generated by Django 2.2.4 on 2019-10-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0002_userform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
