# Generated by Django 2.2.4 on 2019-10-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_auto_20191005_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='country',
            field=models.CharField(blank=True, choices=[('saudi', 'SAUDI'), ('oman', 'OMAN'), ('kuwait', 'KWUAIT')], max_length=250, null=True),
        ),
    ]
