# Generated by Django 2.2.4 on 2019-10-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0004_userform_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='nationality',
            field=models.CharField(blank=True, choices=[('خليجي', 'ليس خليجي')], max_length=250, null=True),
        ),
    ]
