# Generated by Django 2.2.4 on 2019-10-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0005_userform_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='nationality',
            field=models.CharField(blank=True, choices=[('خليجي', 'خليجي'), ('ليس خليجي', 'ليس خليجي')], max_length=250, null=True),
        ),
    ]
