# Generated by Django 2.2.4 on 2019-10-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0006_auto_20191005_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='nationality',
            field=models.CharField(choices=[('خليجي', 'خليجي'), ('ليس خليجي', 'ليس خليجي')], max_length=250, null=True),
        ),
    ]
