# Generated by Django 2.2.4 on 2019-10-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0007_auto_20191005_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='country',
            field=models.CharField(choices=[('saudi arabia +966', 'SAUDI ARABIA +966'), ('oman +968', 'OMAN +968'), ('kuwait +965', 'KWUAIT +965'), ('Qatar +948', 'QATAR +948')], max_length=250, null=True),
        ),
    ]
