# Generated by Django 2.2.4 on 2019-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0008_auto_20191005_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='phone_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
