# Generated by Django 2.2.6 on 2019-10-07 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0009_auto_20191005_0809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='User',
        ),
    ]
